# Generated by Django 4.1.3 on 2023-06-11 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="内容")),
                ("image", models.ImageField(upload_to="", verbose_name="画像")),
                (
                    "score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="満足度",
                    ),
                ),
                ("time", models.DateField()),
            ],
        ),
    ]
