# Generated by Django 4.1.3 on 2023-06-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="time",
            field=models.DateField(verbose_name="日付"),
        ),
    ]
