# Generated by Django 4.1.3 on 2023-06-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_item_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="score",
        ),
    ]
