# Generated by Django 4.1.3 on 2023-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_item_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="user",
        ),
        migrations.AddField(
            model_name="item",
            name="contribute",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
