# Generated by Django 4.1.3 on 2023-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_item_contribute_item_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="user",
            field=models.CharField(max_length=155, verbose_name="ユーザー名"),
        ),
    ]
