# Generated by Django 4.1.3 on 2023-06-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="my_user",
        ),
    ]
